# Generated by Django 2.2.13 on 2021-04-26 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='姓名')),
                ('sequence', models.IntegerField(default=10, unique=True, verbose_name='排序')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='书名')),
                ('state', models.CharField(choices=[('continue', '连载中'), ('done', '完本')], default='continue', max_length=30, verbose_name='状态')),
                ('cover', models.CharField(max_length=70, null=True, verbose_name='封面图')),
                ('description', models.CharField(max_length=300, null=True, verbose_name='内容简介')),
                ('words_count', models.IntegerField(default=0, verbose_name='字数')),
                ('collection_count', models.IntegerField(default=0, verbose_name='收藏数')),
                ('ranking', models.IntegerField(default=0, verbose_name='排名权重')),
                ('latest_chapter', models.CharField(max_length=70, null=True, verbose_name='最新章节')),
                ('latest_chapter_url', models.CharField(max_length=70, null=True, verbose_name='最新章节地址')),
                ('latest_chapter_time', models.DateTimeField(null=True, verbose_name='最后更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Author', verbose_name='作者')),
            ],
            options={
                'verbose_name': '小说',
                'verbose_name_plural': '小说',
            },
        ),
        migrations.CreateModel(
            name='BookSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='名称')),
                ('host', models.CharField(max_length=70, verbose_name='域名')),
                ('book_url', models.CharField(default='https://book.qidian.com/info/{}#Catalog', max_length=70, verbose_name='小说详情地址')),
                ('chapter_url', models.CharField(default='https://book.qidian.com/info/{}#Catalog', max_length=70, verbose_name='小说目录地址')),
                ('need_confirm', models.BooleanField(default=0)),
                ('select_novel_name', models.CharField(default="meta[property='og:title']", max_length=70, verbose_name='书名-选择器')),
                ('select_author', models.CharField(default="meta[property='og:novel:author']", max_length=70, verbose_name='作者-选择器')),
                ('select_cover', models.CharField(default="meta[property='og:image']", max_length=70, verbose_name='封面图-选择器')),
                ('select_description', models.CharField(default="meta[property='og:description']", max_length=70, verbose_name='内容简介-选择器')),
                ('select_state', models.CharField(default="meta[property='og:novel:status']", max_length=70, verbose_name='状态-选择器')),
                ('select_novels_category', models.CharField(default="meta[property='og:novel:category']", max_length=70, verbose_name='分类-选择器')),
                ('select_novel_chapter_name', models.CharField(default='div#voteList a.index', max_length=70, verbose_name='章节标题-选择器')),
                ('select_novel_chapter_url', models.CharField(default='div#voteList a.index', max_length=70, verbose_name='章节地址-选择器')),
                ('select_novel_chapter_content', models.CharField(default='div#voteList a.index', max_length=70, verbose_name='章节内容-选择器')),
                ('select_latest_chapter', models.CharField(default="meta[property='og:novel:latest_chapter_name']", max_length=70, verbose_name='最新章节-选择器')),
                ('select_latest_chapter_url', models.CharField(default="meta[property='og:novel:latest_chapter_url']", max_length=70, verbose_name='最新章节地址-选择器')),
                ('select_latest_chapter_time', models.CharField(default="meta[property='og:novel:update_time']", max_length=70, verbose_name='最后更新时间-选择器')),
                ('sequence', models.IntegerField(default=10, unique=True, verbose_name='排序')),
            ],
            options={
                'verbose_name': '网站来源',
                'verbose_name_plural': '网站来源',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='名称')),
                ('sequence', models.IntegerField(default=10, unique=True, verbose_name='排序')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('sequence', models.IntegerField(default=10, unique=True, verbose_name='排序')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='标题')),
                ('sequence', models.IntegerField(default=10, unique=True, verbose_name='排序')),
                ('content', models.TextField(verbose_name='内容')),
                ('next_chapter_id', models.IntegerField(default=0, verbose_name='下一章节')),
                ('prev_chapter_id', models.IntegerField(default=0, verbose_name='上一章节')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Book', verbose_name='小说')),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.BookSource', verbose_name='网站来源')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, to='novel.Tag', verbose_name='标签'),
        ),
    ]
