# Generated by Django 2.2.13 on 2021-04-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_auto_20210427_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='channel',
            field=models.CharField(choices=[('boy', '男频'), ('girl', '女频'), ('normal', '图书')], default='boy', max_length=30, verbose_name='频道'),
        ),
    ]
