# Generated by Django 2.2.13 on 2020-12-13 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_account', models.CharField(max_length=50, verbose_name='微信账号')),
                ('account_path', models.FilePathField(blank=True, path='./app/static/image/account', verbose_name='账号图片地址')),
                ('online', models.BooleanField(blank=True, default=False, verbose_name='是否已登入')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='是否启用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登入账号')),
            ],
            options={
                'verbose_name': '微信账号',
                'verbose_name_plural': '微信账号',
                'ordering': ['user', 'wx_account'],
                'get_latest_by': 'id',
            },
        ),
    ]
