# Generated by Django 2.2.13 on 2020-12-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechat',
            name='account_path',
        ),
        migrations.AlterField(
            model_name='wechat',
            name='active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='online',
            field=models.BooleanField(default=False, verbose_name='是否已登入'),
        ),
    ]
